import Head from "next/head";
import IconCard from "../components/IconCard";
import LandingHero from "../components/LandingHero";
import FlexGallery from "../components/FlexGallery";
import Heading from "../components/Heading";
import Link from "next/link";
import VideoHero from "../components/VideoHero";

export default function Home() {
  return (
    <div className="container">
      <Head>
        <title>Yin Yang Spa</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.png" />
      </Head>

      <LandingHero />

      <Heading
        mainHeading="Enjoy in the right places"
        subHeading="Enjoy from our spa services at some of our most exotic places."
      />

      <FlexGallery />

      <Heading
        mainHeading="Let us help you"
        subHeading="We can help you choose what service or product is best for you."
      />

      <div className="flex-column justify-center align-center">
        <div className="flex-row space-evenly">
          <IconCard
            heading="Services"
            body="Feel yourself at home with our wide range of services that help you relax and have a great time at our spa."
            img="/images/home/services.svg"
          />
          <IconCard
            heading="Products"
            body="We offer products that help you have a cleaner and more rejuvenated skin. As well as increase your overall health."
            img="/images/home/products.svg"
          />
          <IconCard
            heading="Bar"
            body="Enjoy from our amazing drinks at Yin Yang Spa. Choose drinks that relax and refresh you in an unique way."
            img="/images/home/bar.svg"
          />
        </div>
        <Link href="/team">
          <a className="button mt-40">Contact Team</a>
        </Link>
      </div>

      <VideoHero />
    </div>
  );
}
